[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#[[plugins]]
#repo = 'roxma/nvim-yarp'
##if = '!has("nvim") && has("timers") && has("python3") && system("pip3 show neovim") !=# ""'
#
#[[plugins]]
#repo = 'roxma/vim-hug-neovim-rpc'
##if = '!has("nvim") && has("timers") && has("python3") && system("pip3 show neovim") !=# ""'
#
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
##if = '((has("nvim") || has("timers")) && has("python3")) && system("pip3 show neovim") !=# ""'
